### Bem  vindos 🕸️ 
 _Meu nome é Matheus Lima, tenho 14 anos_
 
 Sou um  estudante do Primeiro ano do Ensinio médio no Colegio Fazenda Velha 🦉, Turma B 
Estou fazendo os cursos do alura sobre programação:)

<!--
**Theuzxvv/Theuzxvv** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
-  How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
